In [1]:
import os
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import entropy

In [2]:
meta = pd.read_csv("/data2/datasets/clobotics/ccth/indices/ccth_sku_metadata_0120.csv")

### Get Product Id List suitable for SKU Classification Task

In [9]:
category_ids = meta[meta.ProductId == meta.CategoryId].ProductId.tolist()

In [10]:
subbrand_other_ids = meta[meta.ProductId == meta.SubBrandId].ProductId.tolist()

In [11]:
meta[pd.isnull(meta.SubBrandId)]

,ProductId,SKUType,Package,UnitCount,Volume,VolumeType,Industry,Juice,CategoryId,Brand,SubBrand,SubBrandId,Series,Flavor,Market,SKUName
260,1037848,tail,NaN,NaN,NaN,NaN,Drink,Beer,1037848,NaN,NaN,NaN,NaN,NaN,Thailand,Beer-Other
261,1037849,tail,NaN,NaN,NaN,NaN,Drink,Wine,1037849,NaN,NaN,NaN,NaN,NaN,Thailand,Wine-Other
262,1037850,tail,NaN,NaN,NaN,NaN,Drink,Sparkling,1037850,NaN,NaN,NaN,NaN,NaN,Thailand,Sparkling-Other
263,1037851,tail,NaN,NaN,NaN,NaN,Drink,Water,1037851,NaN,NaN,NaN,NaN,NaN,Thailand,Water-Other
264,1037852,tail,NaN,NaN,NaN,NaN,Drink,Juice,1037852,NaN,NaN,NaN,NaN,NaN,Thailand,Juice-Other
265,1037853,tail,NaN,NaN,NaN,NaN,Drink,Sports Drink,1037853,NaN,NaN,NaN,NaN,NaN,Thailand,Sports Drink-Other
406,1051447,tail,NaN,NaN,NaN,NaN,Drink,Dairy,1051447,NaN,NaN,NaN,NaN,NaN,Thailand,Dairy-Other
407,1051448,tail,NaN,NaN,NaN,NaN,Drink,Coffee,1051448,NaN,NaN,NaN,NaN,NaN,Thailand,Coffee-Other
409,1051868,tail,NaN,NaN,NaN,NaN,Drink,Tea,1051868,NaN,NaN,NaN,NaN,NaN,Thailand,Tea-Other
410,1051869,tail,NaN,NaN,NaN,NaN,Drink,Energy,1051869,NaN,NaN,NaN,NaN,NaN,Thailand,Energy-Other